#!/bin/bash

source "$HOME/GitPrivate/dotfiles/.config/sketchybar/colors.sh" # Loads all defined colors

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
ITEM_DIR="$HOME/.config/sketchybar/items"
CONFIG_DIR="$HOME/.config/sketchybar"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=25        \
                 blur_radius=30   \
                 position=top     \
                 sticky=off       \
                 padding_left=10  \
                 padding_right=10 \
                 color=$BAR_COLOR

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font="SF Pro:Semibold:14.0"  \
                     icon.color=$BLACK                  \
                     label.font="SF Pro:Semibold:14.0" \
                     label.color=$BLACK                \
                     background.color=$WHITE       \
                     background.corner_radius=6            \
                     background.height=25                  \
                     padding_left=5                    \
                     padding_right=5                   \
                     label.padding_left=5              \
                     label.padding_right=10             \
                     icon.padding_left=10               \
                     icon.padding_right=6
                     
# -- Left Side Items --
source $ITEM_DIR/front_app.sh
source $ITEM_DIR/spaces.sh
#
# -- Right Side Of Notch Items --
source $ITEM_DIR/media.sh
# --- Right Side Items ---
#
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
