#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
sketchybar --bar height=25 \
	blur_radius=25 \
	position=top \
	sticky=off \
	topmost=window \
	padding_left=10 \
	padding_right=10 \
	color=$BAR_COLOR

##### Changing Defaults #####
sketchybar --default icon.font="SF Pro:Semibold:12.0" \
	icon.color=$WHITE \
	label.font="SF Pro:Semibold:12.0" \
	label.color=$WHITE \
	padding_left=1 \
	padding_right=1 \
	label.padding_left=4 \
	label.padding_right=10 \
	icon.padding_left=10 \
	icon.padding_right=4

# -- Left Side Items --
source $ITEM_DIR/front_app.sh

# -- Right Side Items --
source $ITEM_DIR/time.sh
source $ITEM_DIR/date.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/ram_usage.sh

# -- Right Side Of Notch Items --
source $ITEM_DIR/media.sh

##### Adding aerospace layouts #####
sketchybar --add event aerospace_workspace_change

# Add workspaces
for sid in 1 2 3 4 5 6 7; do
    sketchybar --add item space.$sid left \
      --subscribe space.$sid aerospace_workspace_change \
      --set space.$sid \
      drawing=on \
      background.color=0x44ffffff \
      background.corner_radius=0 \
      background.drawing=on \
      background.border_color=0xAAFFFFFF \
      background.border_width=0 \
      background.height=25 \
      icon="$sid" \
      icon.padding_left=10 \
      icon.shadow.distance=4 \
      icon.shadow.color=0xA0000000 \
      label.font="sketchybar-app-font:Regular:16.0" \
      label.padding_right=20 \
      label.padding_left=0 \
      label.y_offset=-1 \
      label.shadow.drawing=off \
      label.shadow.color=0xA0000000 \
      label.shadow.distance=4 \
      click_script="aerospace workspace $sid" \
      script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

# Load Icons on startup
for sid in 1 2 3 4 5 6 7; do
    apps=$(aerospace list-windows --workspace "$sid" | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')
    
    sketchybar --set space.$sid drawing=on
    
    icon_strip=" "
    if [ "${apps}" != "" ]; then
      while read -r app; do
        icon_strip+=" $($CONFIG_DIR/plugins/icon_map_fn.sh "$app")"
      done <<<"${apps}"
    else
      icon_strip=""
    fi
    sketchybar --set space.$sid label="$icon_strip"
done

##### Finalizing Setup #####
sketchybar --update
