#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=25 \
	blur_radius=25 \
	position=top \
	sticky=off \
	padding_left=10 \
	padding_right=10 \
	color=$BAR_COLOR

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font="SF Pro:Semibold:12.0" \
	icon.color=$WHITE \
	label.font="SF Pro:Semibold:12.0" \
	label.color=$WHITE \
	padding_left=1 \
	padding_right=1 \
	label.padding_left=4 \
	label.padding_right=10 \
	icon.padding_left=10 \
	icon.padding_right=4

# -- Left Side Items --
# source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

# -- Right Side Items --
source $ITEM_DIR/time.sh
source $ITEM_DIR/date.sh
#source $ITEM_DIR/wifi.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/ram_usage.sh

# -- Right Side Of Notch Items --
source $ITEM_DIR/media.sh

##### Adding aeropsace layouts #####

# Add the aerospace_workspace_change event we specified in aerospace.toml
sketchybar --add event aerospace_workspace_change

# Add workspaces for all monitors
#for monitor in $(aerospace list-monitors --format "%{monitor-appkit-nsscreen-screens-id}"); do
#  for sid in $(aerospace list-workspaces --monitor "$monitor"); do
#    # Determine which display this workspace should be shown on
#    display_id="1"
#    if [ "$sid" -ge 6 ] && [ "$sid" -le 7 ]; then
#      display_id="2"
#    fi
    
for sid in 1 2 3 4 5 6 7; do
    sketchybar --add item space.$sid left \
      --set space.$sid display="$display_id" \
      --subscribe space.$sid aerospace_workspace_change \
      --set space.$sid \
      drawing=on \
      background.color=0x44ffffff \
      background.corner_radius=0 \
      background.drawing=on \
      background.border_color=0xAAFFFFFF \
      background.border_width=0 \
      background.height=25 \
      icon="$sid" \
      icon.padding_left=10 \
      icon.shadow.distance=4 \
      icon.shadow.color=0xA0000000 \
      label.font="sketchybar-app-font:Regular:16.0" \
      label.padding_right=20 \
      label.padding_left=0 \
      label.y_offset=-1 \
      label.shadow.drawing=off \
      label.shadow.color=0xA0000000 \
      label.shadow.distance=4 \
      click_script="aerospace workspace $sid" \
      script="$CONFIG_DIR/plugins/aerospace.sh $sid"
#  done
done

# Load Icons on startup for all monitors
#for monitor in $(aerospace list-monitors); do
#  for sid in $(aerospace list-workspaces --monitor "$monitor" --empty no); do

for sid in 1 2 3 4 5 6 7; do
    apps=$(aerospace list-windows --workspace "$sid" | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')

    sketchybar --set space.$sid drawing=on

    icon_strip=" "
    if [ "${apps}" != "" ]; then
      while read -r app; do
        icon_strip+=" $($CONFIG_DIR/plugins/icon_map_fn.sh "$app")"
      done <<<"${apps}"
    else
      icon_strip=""
    fi
    sketchybar --set space.$sid label="$icon_strip"
#  done
done


#front app
source "$ITEM_DIR/front_app.sh"


##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.
sketchybar --update
