-- Neue Keybindings für Buffer-Wechsel
-- vim.keymap.set('n', '<C-n>', ':bnext<CR>', { noremap = true, silent = true })
-- vim.keymap.set('n', '<C-p>', ':bprev<CR>', { noremap = true, silent = true })
